version: '3.8'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: sherly
      POSTGRES_USER: sherly
      POSTGRES_PASSWORD: sherly
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    network_mode: "bridge"
