version: '3.8'
services:
  db:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      cockroachdb_net:
        aliases:
          - node_1
networks:
  cockroachdb_net:
    driver: bridge
